version: '3'
services:
  filebeat:
    build:
      context: .
    image: zomato/filebeat-kafka
    volumes:
      - "/var/lib/docker/containers:/var/lib/docker/containers"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
     KAFKA_HOSTS: kafka:9092
  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
    ports:
      - 9092:9092
