version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - postgres:/var/lib/postgresql/data
  superset:
    image: zomato/superset
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8088:8088"
  worker:
    image: zomato/superset
    restart: always
    depends_on:
      - postgres
      - redis
    command: celery worker --app=superset.sql_lab:celery_app --pool=gevent -Ofair -c 2
volumes:
  postgres:
    external: false
  redis:
    external: false
